### PR TITLE
[MM-60408] Replaced chars with HTML entities in reminder posts

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- Replaced chars with HTML entities in reminder posts

#### Screenshots
Before:
image

After: 
image

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-60408

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]

**Review by enzowritescode — APPROVED** [review]

**Comment by AayushChaudhary0001** [comment]
@raghavaggarwal2308 This PR was reviewed and I found an issue regarding some markdowns
Please refer the below screenshots:-

on MS calendar
image

on MM
image


This seems to have a handling issue on Mattermost, please verify the same.

**Comment by Kshitij-Katiyar** [comment]
> @raghavaggarwal2308 This PR was reviewed and I found an issue regarding some markdowns Please refer the below screenshots:-
> 
> on MS calendar image
> 
> on MM image
> 
> This seems to have a handling issue on Mattermost, please verify the same.

Hey @AayushChaudhary0001, The issue you have reported is not related to this PR, Please log a separate issue for this.
However a similar issue is found in the reminder post, A MSCalendar event with the ````test```$$qa$$**new**##few##` title is rendered as below
Screenshot from 2024-10-23 16-12-28

I looked into this issue but the `MarkdownToHTMLEntities` is working fine and converting the event subject to an equivalent HTML entity. The issue is with the rendering of slack attachment on the mattermost side

**Comment by hanzei** [comment]
That seems odd. Are we using a different rendering method in message attachments?

**Comment by Kshitij-Katiyar** [comment]
> @raghavaggarwal2308 This PR was reviewed and I found an issue regarding some markdowns Please refer the below screenshots:-
> 
> on MS calendar image
> 
> on MM image
> 
> This seems to have a handling issue on Mattermost, please verify the same.

created an [issue](https://github.com/mattermost/mattermost-plugin-mscalendar/issues/430) for this and the issue reported by me

**Review by AayushChaudhary0001 — APPROVED** [review]
Approving this PR, since a new Github issue has been created for the issue reported above

**Pull request merged**
