### PR TITLE
Release 1.1.1

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-mscalendar/pull/245

### CODE REVIEW

**Comment by DHaussermann** [comment]
Thanks @mickmister for opening up this version bump branch. I can a quick smoke test for release testing this. 

Is there a change needed for GitHub actions to get a binary included in the build CI checks?

**Comment by DHaussermann** [comment]
> Thanks @mickmister for opening up this version bump branch. I can a quick smoke test for release testing this.
> 
> Is there a change needed for GitHub actions to get a binary included in the build CI checks?

One other thing on this - I was able to local testing with help from @mickmister where the config was changed locally to also include Darwin ARM when it compiles but that's not something that happens now with the `make` maybe something we could address here?

**Comment by DHaussermann** [comment]
On last piece of information to share on this. When I try to upload the compile binary to a Cloud server the UI hangs for a moment and I see `invalid response from server` Seems something is going wrong before it tries to start up the binary. I don't see anything obviously related in server logs when this happens.  I have also made sure the file upload size limit is not being exceeded.

**Comment by mickmister** [comment]
Closing in favor of https://github.com/mattermost/mattermost-plugin-mscalendar/pull/250

**Pull request closed without merging**
