### PR TITLE
Revert "Implement autorespond feature (#188)"

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR is a temporary fix for an issue that's blocking the v1.1.0 release. https://mattermost.atlassian.net/browse/MM-38426

With the Autorespond feature, the post props for the settings panel exceeds the limit of runes allowed. This makes it so the settings panel post has an error and cannot be shown to the user. This was not caught in testing because the Autoresponder PR #188 was merged with testing deferred to release testing.

This PR reverts the Autorespond feature so this issue with the settings panel no longer happens. cc @larkox @catalintomai @aaronrothschild

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-38426

### CODE REVIEW

**Comment by mickmister** [comment]
The PR is currently in a bad state with plugin API methods not existing

`# github.com/mattermost/mattermost-plugin-mscalendar/server/api
api/post_action.go:183:31: api.Env.Dependencies.PluginAPI.GetMattermostUserStatus undefined (type mscalendar.PluginAPI has no field or method GetMattermostUserStatus)`

**Comment by catalintomai** [comment]
cc: @DHaussermann - fyi wrt to status of MM-38426

**Review by catalintomai — APPROVED** [review]

**Review by larkox — APPROVED** [review]
LGTM. Is there any ticket to reimplement this?

**Comment by DHaussermann** [comment]
@mickmister  I can't build this with `make dist` I get
```
./build/bin/manifest apply
mkdir -p server/dist;
cd server && env GOOS=linux GOARCH=amd64 /usr/local/go/bin/go build  -o dist/plugin-linux-amd64;
# github.com/mattermost/mattermost-plugin-mscalendar/server/api
api/post_action.go:183:31: api.Env.Dependencies.PluginAPI.GetMattermostUserStatus undefined (type mscalendar.PluginAPI has no field or method GetMattermostUserStatus)
make: *** [server] Error 2
```
Can you reproduce this?

**Comment by mickmister** [comment]
@DHaussermann This is ready for QA

Ticket to re-implement autorespond https://github.com/mattermost/mattermost-plugin-mscalendar/issues/227

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Feature successfully reverted. No visible slash command and settings to configure.
- This resolves the issue with not being able to open the settings pannel
- Build issues resolved
- Nil error on status resolved 
LGTM!

Thanks @mickmister please merge

**Pull request merged**
