### PR TITLE
Add Fallback to Slack Attachments

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Add Fallback to Slack Attachments, so text is written in the mail sent on notifications and other clients that may not accept Slack Attachments.

#### Ticket Link
None

### CODE REVIEW

**Comment by DHaussermann** [comment]
@larkox  seems I can't pull master in. I need a fix you merged yesterday.

**Comment by larkox** [comment]
@DHaussermann Done :smile:

**Comment by DHaussermann** [comment]
@larkox I'm not sure this solved the issue where there is no post content. 
Steps:
- Deployed this build
- Create upcoming event for target user
- Enable email notification and set status to Offline
- Wait until the job ran and MS Cal bot sent me a DM about status update
- Check corresponding email
**Observed**
Upcoming event post DM email has content but, Status change DM email is empty.
Screen Shot 2020-12-02 at 5 03 34 PM

**Comment by DHaussermann** [comment]
@larkox let me know if you have any thoughts on this ☝️

**Comment by larkox** [comment]
@DHaussermann After looking at the email related code, I see that it does not consider the fallback information to generate the e-mail. I still think that adding the fallback is useful, but it does not resolves the problem.

**Comment by DHaussermann** [comment]
Thanks @larkox 
So, this was regression tested with no negative impacts. I have no issue with it merging.   


That said can we make sure the merge does not close https://github.com/mattermost/mattermost-plugin-mscalendar/issues/169 as this issue described by @aaronrothschild  is still an resolved and will need a follow-up PR.

**Review by DHaussermann — APPROVED** [review]

**Pull request merged**
