### PR TITLE
mm 198 - Handle case where a user's refresh token expires fixes #198 

### LINKED ISSUE #198: Refresh token expiring due to user inactivity
Per the discussion in https://github.com/mattermost/mattermost-plugin-mscalendar/issues/15#issuecomment-585033566, it was determined that we should allow the OAuth2 library to handle access tokens and refresh tokens with the library's default behavior.

The refresh token is used to retrieve an access token whenever we need to perform an operation in Microsoft's system. A customer's log reports an error that says ` The refresh token has expired due to inactivity`. This error is occurring during the Renew Subscription job. The customer said this error is printed to the logs every night at midnight.

> (log ERROR) Error renewing subscription. err=msgraph RenewSubscription: Patch "https://graph.microsoft.com/v1.0/subscriptions/REDACTED": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-07-23T12:22:48.1096407Z and was inactive for 90.00:00:00.\r\nTrace ID: b40f4014-73bb-40f3-b90d-cd42d78c9600\r\nCorrelation ID: 1bb86522-a8e8-45a2-9966-2d11a892c925\r\nTimestamp: 2020-11-05 00:00:00Z","error_codes":[700082],"timestamp":"2020-11-05 00:00:00Z","trace_id":"b40f4014-73bb-40f3-b90d-cd42d78c9600","correlation_id":"1bb86522-a8e8-45a2-9966-2d11a892c925","error_uri":"https://login.microsoftonline.com/error?code=700082"}

Microsoft's [docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#token-lifetimes-with-confidential-client-refresh-tokens) state that their refresh tokens do not expire. Here are two routes we may take:

- Auto-renew refresh tokens. I think this may be undesirable on Microsoft's side. But other than that I don't think it's a problem.
- Handle this error when it happens, mark the user as inactive locally, and have the user re-authenticate the next time they try to do something with the plugin.

More context here https://community-daily.mattermost.com/core/pl/u7jyh7dokpdtfcq49keu6peofe

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/iwcsqwh8j38cigj1zasqhn9nkr) *by @mickmister*._

### PR DESCRIPTION
**Pull request by sibasankarnayak**
Implementation of refresh token 

ticket here
https://github.com/mattermost/mattermost-plugin-mscalendar/issues/198

### CODE REVIEW

**Comment by maisnamrajusingh** [comment]
@hanzei  who would be a good person to talk about this ? @mickmister mentioned that he is no longer maintaining this, needed some advice on this as it seems the oauth2 library already refreshes the token.

**Comment by mickmister** [comment]
@maisnamrajusingh Either me or @levb would be the best person to discuss this.

> it seems the oauth2 library already refreshes the token.

The library refreshes the `access token`, but we want an updated `refresh token` to be stored in our database. Can you check if the `oauth2` library mutates the `oauth2.Token` struct with a new refresh token when we make a request to Microsoft's API?

**Comment by mickmister** [comment]
Here's a relevant issue on this topic: https://github.com/mattermost/mattermost-plugin-mscalendar/issues/15

Also this resource from Microsoft's docs:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#token-lifetimes-with-confidential-client-refresh-tokens

**Comment by larkox** [comment]
@maisnamrajusingh  I did some fixes regarding this on the ServiceNow App. It is not exactly the same architecture, but the theory is the same. You can find here the related commit:

https://github.com/mattermost/mattermost-app-servicenow/pull/15/commits/91e07f6718455e8440d4ed5c3d01eb6437446f0d

Feel free to ask me if you need more info.

**Comment by maisnamrajusingh** [comment]
> @maisnamrajusingh I did some fixes regarding this on the ServiceNow App. It is not exactly the same architecture, but the theory is the same. You can find here the related commit:
> 
> [mattermost/mattermost-app-servicenow@91e07f6](https://github.com/mattermost/mattermost-app-servicenow/commit/91e07f6718455e8440d4ed5c3d01eb6437446f0d)
> 
> Feel free to ask me if you need more info.

Will take a look together with Siba. Thanks, this one is a bit confusing.

**Pull request closed without merging**
