### PR TITLE
[MM-60217]: Converted the reserved Markdown characters to their HTML entity equivalents

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
#### Summary
Converted the reserved Markdown characters to their HTML entity equivalents. So no markdown can be rendered

### CODE REVIEW

**Review by wiggin77 — CHANGES_REQUESTED** [review]
Thanks @Kshitij-Katiyar .   I will always ask for unit tests for new code like this.

**Comment by wiggin77** [comment]
@Kshitij-Katiyar see comment here:  https://mattermost.atlassian.net/browse/MM-60217?focusedCommentId=169185

**Comment by enzowritescode** [comment]
I am still seeing rendered markdown when events are updated

md_link

**Review by enzowritescode — COMMENTED** [review]
I am still seeing rendered markdown when events are updated

**Comment by Kshitij-Katiyar** [comment]
@enzowritescode fixed it.

**Comment by enzowritescode** [comment]
update

This does not look correct

**Comment by Kshitij-Katiyar** [comment]
> update
> 
> This is not getting displayed correctly

@enzowritescode Can you share whats the event name is now after the updation ?

**Comment by enzowritescode** [comment]
The event is titled "[DuckDuckGo](https://duckduckgo.com/)" (but without the quotes)

**Comment by raghavaggarwal2308** [comment]
@enzowritescode @wiggin77 

> The event is titled `[DuckDuckGo](https://duckduckgo.com/)`

We are unable to render any html code at the end of URL on Mattermost. I think is is being considered as a query param instead of a html code. Look at the screenshots for more clarity. Do you have any suggestions on how we can fix it?

image
image
image

**Comment by enzowritescode** [comment]
The front-end must be performing some processing on things that it believes to be markdown which we don't want. I will look into this some more.

```
<a class="theme markdown__link" href="https://duckduckgo.com/&amp;#41" rel="noreferrer" target="_blank">https://duckduckgo.com/&amp;#41</a>
```

**Review by wiggin77 — APPROVED** [review]

**Review by enzowritescode — APPROVED** [review]

**Comment by enzowritescode** [comment]
@Kshitij-Katiyar escaping the square brackets and parenthesis wasn't enough. I added forward slash and period so plain URLs wouldn't end up getting treated as links. I also put the the `replacements` map in numerical order so it was a little easier to read.

**Comment by AayushChaudhary0001** [comment]
I was testing this PR and found an issue in this PR.
Text if entered in strikethrough format in MS Calendar is still reflected as strikethrough text in Mattermost, the rest of everything works fine, but this strikethrough needs to be fixed.

I am attaching a screenshot below:-

image

**Comment by raghavaggarwal2308** [comment]
@AayushChaudhary0001 The above issue should be fixed now, please re-test

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested this PR after the fix, strikethrough text is displayed fine now. Apart from this, every other markdown has not been impacted due to the lastest fix. Everything works fine, LGTM. Approved.

**Pull request merged**
