### PR TITLE
Fix missing remote user id in daily summary settings

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

The remote user ID was not being set properly when creating the user's daily summary settings.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-mscalendar/issues/130

### CODE REVIEW

**Comment by DHaussermann** [comment]
@mickmister  I'm still having issues making the daily summary work on this PR. Maybe I'm seeing more than 1 issue?

1. I still saw the error occur once. Note the deployment matches the commit hash. 
SummaryError1

2. Afterwards the job does not see that my users needs a summary delivered when I rescheduled the summary to test again.
SummaryError2

Testing is ongoing. I'll see if I can repo with multiple users.

**Comment by mickmister** [comment]
@DHaussermann My previous fix did not properly take into account the current state of your kvstore. The issue would not affect users that have not connected before that fix. I've updated this PR to take this into account.

But this brings about my point of how we are storing these settings. I brought it up in one of our meetings and the response was to keep it how it is because it works. I will assess how much work/risk it will take to store them where the rest of the user's settings are, and create a PR for it if it seems practical.

**Comment by DHaussermann** [comment]
@mickmister I'm seeing a build error when running the full `make` now. Is this something you can resolve? 
```
# github.com/mattermost/mattermost-plugin-mscalendar/server/mscalendar
server/mscalendar/daily_summary.go:57:6: no new variables on left side of :=
# github.com/mattermost/mattermost-plugin-mscalendar/server/mscalendar
vet: server/mscalendar/daily_summary.go:57:6: no new variables on left side of :=
make: *** [govet] Error 2

**Comment by mickmister** [comment]
Thanks @DHaussermann it's resolved now

**Comment by mickmister** [comment]
@DHaussermann Closing in favor of https://github.com/mattermost/mattermost-plugin-mscalendar/pull/141

**Pull request closed without merging**
