### PR TITLE
[GH-367] Remove "prompt" param from auth code URL

### LINKED ISSUE #367: Account connection does not work
This is the sequence of steps, when I try to connect the plugin to my M365 account:

1. I click on the bot message: 
grafik

2. A window pops up where I can choose my M365 account. It says I'm already logged in ("Angemeldet"), probably because I've also installed and configured the [Teams meeting plugin](https://github.com/mattermost-community/mattermost-plugin-msteams-meetings): 
grafik

3. This message box is shown where it says that certain permissions are required, that need to be approved by an administrator. When I click on "Genehmigungsanforderung", administrators get an approval request: 
grafik

4. I approve the permission request in the azure portal

5. I try again to connect the plugin to my M365 account, but I still get the same message box as in step 3, where I can create a new approval request despite that the previous one has already been approved.

That's how it played out yesterday. I thought maybe waiting a day would change something, but it's just the same today.
I've configured the plugin as described [in the documentation](https://github.com/mattermost/mattermost-plugin-mscalendar/blob/master/docs/admin-guide.md#configuration). The configuration was very similar to the MS Teams plugin, which works just fine. When connecting the Teams plugin with my M365 account, There was no permission approval needed, I did not get a message like I did here in step 3.

Kind regards!

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
##### Issue:
- According to the [issue linked below](https://github.com/mattermost/mattermost-plugin-mscalendar/issues/367), the users are not able to accept the permissions in the modal. That modal [was not present](https://github.com/mattermost/mattermost-plugin-mscalendar/issues/367#issuecomment-2135402695) in the previous plugin release and the users were able to connect just by clicking the link from MM.
- The modal is occurring because of a [code change](https://github.com/mattermost/mattermost-plugin-mscalendar/blob/b4f752d6669a9958e7b7b16c757d2d1e5dc7f8a6/calendar/engine/oauth2.go#L51) in [this PR](https://github.com/mattermost/mattermost-plugin-mscalendar/pull/267/files). The [prompt param](https://pkg.go.dev/golang.org/x/oauth2@v0.15.0#section-readme) in the URL is forcing the users to accept the permission the oauth app is requesting on every connection.

##### Fix
- Remove "prompt" param from auth code URL.

#### Ticket Link
Fixes #367

### CODE REVIEW

**Comment by wiggin77** [comment]
@raghavaggarwal2308 some binaries got checked in.  Please remove.

**Review by wiggin77 — CHANGES_REQUESTED** [review]
Some binaries got checked in.  Please remove.

**Review by wiggin77 — APPROVED** [review]

**Review by enzowritescode — APPROVED** [review]

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Who is going to do the security review for this PR?

**Comment by wiggin77** [comment]
> @wiggin77 Who is going to do the security review for this PR?

`enzowritescode` is from our security team.   Reviews are complete.

**Pull request merged**
