### PR TITLE
Update system admin check in api.go

### PR DESCRIPTION
**Pull request by chetanyakan**

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
Thanks @chetanyakan!

**Comment by DHaussermann** [comment]
@chetanyakan or @mickmister, can you provide some context around this change?
1. Does this resolve a bug that existed before this change?
2. Can you provide an example of when this is called for regression testing?

**Comment by mickmister** [comment]
@DHaussermann Looks like the function being used now is slightly more robust, but I can't think of an existing problem this change is solving. I think before this change someone with a role of `system_admin_foobar` would have been treated as a sysadmin before this PR, but that doesn't seem like something realistic.

**Comment by jasonblais** [comment]
@DHaussermann kind reminder to help with QA review :)

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- No known functional impact
- Used undocumented `/mscalendar availability all` to confirm the plugin respects roles accurately
- No other regression testing applicable

LGTM!

Thanks @chetanyakan for this enhancement!

**Pull request merged**
