### PR TITLE
use api for license and fix tests

### PR DESCRIPTION
**Pull request by cjmartian**
#### Summary

This changes the license check to use the API. I've also incorporated some tests fixes here.
#### Ticket Link

https://github.com/mattermost/mattermost-plugin-mscalendar/issues/194

### CODE REVIEW

**Comment by cjmartian** [comment]
Also it looks like this repo isn't eligible for Hacktoberfest, not that it matters too much 👀

**Comment by jasonblais** [comment]
@cjmartian It will be soon! We're writing a script to add the `hacktoberfest` topic to all our repositories :)

**Review by larkox — APPROVED** [review]
LGTM. Thanks! :tada:

**Review by mickmister — APPROVED** [review]
Great work!!

**Comment by cjmartian** [comment]
Thank you @mickmister

**Comment by hanzei** [comment]
This PR can be merged without QA review. I did a quick local test.

**Pull request merged**
